// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFseQCL2VAWypegYvfdX71cg2ZM4eyBGo',
    appId: '1:820592078503:web:5f5f689b71fcd7fa84f582',
    messagingSenderId: '820592078503',
    projectId: 'chat-app-c9ed3',
    authDomain: 'chat-app-c9ed3.firebaseapp.com',
    databaseURL: 'https://chat-app-c9ed3-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-c9ed3.appspot.com',
    measurementId: 'G-M76XG0TNN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsXDxa9Zqi0Q409PVAYpVuoPDAQOmHsdg',
    appId: '1:820592078503:android:a3138aac890feda484f582',
    messagingSenderId: '820592078503',
    projectId: 'chat-app-c9ed3',
    databaseURL: 'https://chat-app-c9ed3-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-c9ed3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7vLEUgrkq5MYY5W9lHCmnydnuno_coOY',
    appId: '1:820592078503:ios:0b2464f987b7cd8084f582',
    messagingSenderId: '820592078503',
    projectId: 'chat-app-c9ed3',
    databaseURL: 'https://chat-app-c9ed3-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-c9ed3.appspot.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7vLEUgrkq5MYY5W9lHCmnydnuno_coOY',
    appId: '1:820592078503:ios:0b2464f987b7cd8084f582',
    messagingSenderId: '820592078503',
    projectId: 'chat-app-c9ed3',
    databaseURL: 'https://chat-app-c9ed3-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-c9ed3.appspot.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFseQCL2VAWypegYvfdX71cg2ZM4eyBGo',
    appId: '1:820592078503:web:5060c4657b9e163684f582',
    messagingSenderId: '820592078503',
    projectId: 'chat-app-c9ed3',
    authDomain: 'chat-app-c9ed3.firebaseapp.com',
    databaseURL: 'https://chat-app-c9ed3-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-c9ed3.appspot.com',
    measurementId: 'G-9G8RC387GV',
  );
}
